/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iSablierSol from "./ISablier.sol";
export type { iSablierSol };
export type { IStaking } from "./IStaking";
