/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interface from "./interface";
export { EvoxGovernor__factory } from "./EvoxGovernor__factory";
export { EvoxSablier__factory } from "./EvoxSablier__factory";
export { EvoxStaking__factory } from "./EvoxStaking__factory";
export { EvoxToken__factory } from "./EvoxToken__factory";
