/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interface from "./interface";
export type { interface };
export type { EvoxGovernor } from "./EvoxGovernor";
export type { EvoxSablier } from "./EvoxSablier";
export type { EvoxStaking } from "./EvoxStaking";
export type { EvoxToken } from "./EvoxToken";
