/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20TokenSol from "./ERC20Token.sol";
export type { erc20TokenSol };
import type * as ozGovernorSol from "./OZGovernor.sol";
export type { ozGovernorSol };
import type * as clock from "./clock";
export type { clock };
import type * as interface from "./interface";
export type { interface };
import type * as sabilerSol from "./sabiler.sol";
export type { sabilerSol };
import type * as stakingSol from "./staking.sol";
export type { stakingSol };
